### PR TITLE
alternative mock event properties

### PR DESCRIPTION
**Pull request by rachelriv**
@cbillingham Please let me know what you think of this. I thought some of the names here are a bit more descriptive. I also changed `id` to `eventID` since I think we might ultimately use a relational database, so the distinction help clarify things.

### CODE REVIEW

**Comment by cbillingham** [comment]
@rachelriv These look much better. Thanks for this. I think we should decide as a group whether we want one Unix timestamp or individual variables. It changes how we process and interpret on the front-end. I'm sort of leaning toward individual variables right now. May be easier to handle timezone and less work for the front end people to convert Unix timestamp and extract entities. However we are then adding a few more variables.

**Comment by cbillingham** [comment]
@rachelriv wait. Don't merge yet. There's a typo on line 75

**Comment by rachelriv** [comment]
Thanks for checking everything so thoroughly guys! Should be good now.

**Comment by jtfennell** [comment]
This looks good to merge, after that https is changed.

**Pull request closed without merging**
