### PR TITLE
Jsc/fb api mod

### PR DESCRIPTION
**Pull request by juansc**
Hey. I made these changes to the facebook route so that we get all the LMU accounts. As I said in an earlier meeting, the previous implementation didn't allow us to get the id for the LMU English Department. If we give make a request for a page's URL, we will get the correct id.

Let me know what you guys think. Please correct me if I wrote any bad coffeescript.

### CODE REVIEW

**Comment by juansc** [comment]
I fixed the tests because I was doing async testing incorrectly. Should be correct now.

**Comment by cbillingham** [comment]
looks good to me Juan
once the social media API is up on Heroku (which I think it might be already), should we update the tests to use the heroku one?

**Comment by rachelriv** [comment]
LGTM Juan!

**Comment by juansc** [comment]
Hey you guys I've noticed that if I run the tests multiple times some facebook names don't pass consistently. I think this may be a result of the async code taking longer than 2 seconds. For example, on one of my runs Men's Basketball failed, but when I ran it a second time it passed. I'm not too familiar with [promises](https://strongloop.com/strongblog/promises-in-node-js-with-q-an-alternative-to-callbacks/), but I believe they run to completion and we won't get the same problem with the code timing out.

That being said, only the test need to be changed. I would like to merge this pull request and make another branch where I change the tests to use promises instead of callbacks.

**Comment by rtoal** [comment]
@cbillingham Maybe I misunderstood the question, but you don't want tests in your codebase that depend on heroku being up. Automated integration tests should run against an embedded (in-memory) http server.

**Comment by rtoal** [comment]
@juansc If you have code taking too long, it shouldn't matter whether it is a callback or a promise. When you set up mocha-based tests you can set a duration threshold for "slow tests" such that any test taking too long will fail. These are command line flags you can set when running mocha:

```
 -s, --slow <ms>                         "slow" test threshold in milliseconds [75]
 -t, --timeout <ms>                      set test-case timeout in milliseconds [2000]
```

You can try with `-t 4000`.

**Comment by juansc** [comment]
@rtoal Thanks! Now a bunch of the ones that were failing due to a timeout are fine!

**Comment by juansc** [comment]
Merging.

**Pull request merged**
